import 'package:cloud_firestore/cloud_firestore.dart';

class HouseModel {
  HouseModel({
    required this.id,
    required this.thumbnail,
    required this.interior1,
    required this.interior2,
    required this.images,
    required this.groundL,
    required this.groundW,
    required this.ghalway,
    required this.gwardrobe,
    required this.ghall,
    required this.gbedroom,
    required this.gbathroom,
    required this.gliving,
    required this.gkitchen,
    required this.gpantry,
    required this.grestroom,
    required this.atticL,
    required this.atticW,
    required this.ahalway,
    required this.awardrobe,
    required this.ahall,
    required this.abedroom,
    required this.abathroom,
    required this.aliving,
    required this.akitchen,
    required this.apantry,
    required this.arestroom,
    required this.dhalway,
    required this.dwardrobe,
    required this.dhall,
    required this.dbedroom,
    required this.dbathroom,
    required this.dliving,
    required this.dkitchen,
    required this.dpantry,
    required this.drestroom,
    required this.technology,
    required this.psoCost,
    required this.turnkeyCost,
  });

  String id;
  String thumbnail;
  String interior1;
  String interior2;
  List<String> images;
  String groundL;
  String groundW;
  String ghalway;
  String gwardrobe;
  String ghall;
  String gbedroom;
  String gbathroom;
  String gliving;
  String gkitchen;
  String gpantry;
  String grestroom;
  String atticL;
  String atticW;
  String ahalway;
  String awardrobe;
  String ahall;
  String abedroom;
  String abathroom;
  String aliving;
  String akitchen;
  String apantry;
  String arestroom;
  String dhalway;
  String dwardrobe;
  String dhall;
  String dbedroom;
  String dbathroom;
  String dliving;
  String dkitchen;
  String dpantry;
  String drestroom;
  String technology;
  String psoCost;
  String turnkeyCost;

  factory HouseModel.fromJson(QueryDocumentSnapshot json) => HouseModel(
        id: json.id,
        thumbnail: json["thumbnail"],
        interior1: json["interior1"],
        interior2: json["interior2"],
        images: List<String>.from(json["images"].map((x) => x)),
        gbathroom: json["gbathroom"],
        gbedroom: json["gbedroom"],
        ghall: json["ghall"],
        ghalway: json["ghalway"],
        gkitchen: json["gkitchen"],
        gliving: json["gliving"],
        grestroom: json["grestroom"],
        gpantry: json["gpantry"],
        groundL: json["groundL"],
        groundW: json["groundW"],
        gwardrobe: json["gwardrobe"],
        atticL: json["atticL"],
        atticW: json["atticW"],
        abathroom: json["abathroom"],
        abedroom: json["abedroom"],
        ahall: json["ahall"],
        ahalway: json["ahalway"],
        akitchen: json["akitchen"],
        aliving: json["aliving"],
        arestroom: json["arestroom"],
        apantry: json["apantry"],
        awardrobe: json["awardrobe"],
        dbathroom: json["dbathroom"],
        dbedroom: json["dbedroom"],
        dhall: json["dhall"],
        dhalway: json["dhalway"],
        dkitchen: json["dkitchen"],
        dliving: json["dliving"],
        drestroom: json["drestroom"],
        dpantry: json["dpantry"],
        dwardrobe: json["dwardrobe"],
        technology: json["technology"],
        psoCost: json["psoCost"],
        turnkeyCost: json["turnkeyCost"],
      );
}
/* class HouseModel {
  HouseModel({
    required this.id,
    required this.images,
    required this.groundL,
    required this.groundW,
    required this.ghalway,
    required this.gwardrobe,
    required this.ghall,
    required this.gbedroom,
    required this.gbathroom,
    required this.gliving,
    required this.gkitchen,
    required this.gpantry,
    required this.grestroom,
    required this.atticL,
    required this.atticW,
    required this.ahalway,
    required this.awardrobe,
    required this.ahall,
    required this.abedroom,
    required this.abathroom,
    required this.aliving,
    required this.akitchen,
    required this.apantry,
    required this.arestroom,
    required this.dhalway,
    required this.dwardrobe,
    required this.dhall,
    required this.dbedroom,
    required this.dbathroom,
    required this.dliving,
    required this.dkitchen,
    required this.dpantry,
    required this.drestroom,
    required this.technology,
    required this.psoCost,
    required this.turnkeyCost,
  });

  String id;
  List<String> images;
  int groundL;
  int groundW;
  int ghalway;
  int gwardrobe;
  int ghall;
  int gbedroom;
  int gbathroom;
  int gliving;
  int gkitchen;
  int gpantry;
  int grestroom;
  int atticL;
  int atticW;
  int ahalway;
  int awardrobe;
  int ahall;
  int abedroom;
  int abathroom;
  int aliving;
  int akitchen;
  int apantry;
  int arestroom;
  int dhalway;
  int dwardrobe;
  int dhall;
  int dbedroom;
  int dbathroom;
  int dliving;
  int dkitchen;
  int dpantry;
  int drestroom;
  String technology;
  int psoCost;
  int turnkeyCost;

  factory HouseModel.fromJson(QueryDocumentSnapshot json) => HouseModel(
        id: json.id,
        images: List<String>.from(json["images"].map((x) => x)),
        gbathroom: json["gbathroom"],
        gbedroom: json["gbedroom"],
        ghall: json["ghall"],
        ghalway: json["ghalway"],
        gkitchen: json["gkitchen"],
        gliving: json["gliving"],
        grestroom: json["grestroom"],
        gpantry: json["gpantry"],
        groundL: json["groundL"],
        groundW: json["groundW"],
        gwardrobe: json["gwardrobe"],
        atticL: json["atticL"],
        atticW: json["atticW"],
        abathroom: json["abathroom"],
        abedroom: json["abedroom"],
        ahall: json["ahall"],
        ahalway: json["ahalway"],
        akitchen: json["akitchen"],
        aliving: json["aliving"],
        arestroom: json["arestroom"],
        apantry: json["apantry"],
        awardrobe: json["awardrobe"],
        dbathroom: json["dbathroom"],
        dbedroom: json["dbedroom"],
        dhall: json["dhall"],
        dhalway: json["dhalway"],
        dkitchen: json["dkitchen"],
        dliving: json["dliving"],
        drestroom: json["drestroom"],
        dpantry: json["dpantry"],
        dwardrobe: json["dwardrobe"],
        technology: json["technology"],
        psoCost: json["psoCost"],
        turnkeyCost: json["turnkeyCost"],
      );
} */
